apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /generate-values
  name: generate-values
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|generate-values
source: |-
  load("krmfn.star", "krmfn")
  def set_values(resources):
    # this package can be cloned manually and used without injection; in that case base
    # the repository name on the package name
    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "kptfile.kpt.dev"):
        clusterName = r["data"]["name"]
    # if a WorkloadCluster exists, and was injected, then use that for the name
    for r in resources:
      if krmfn.match_gvk(r, "infra.nephio.org/v1alpha1", "WorkloadCluster") and "annotations" in r["metadata"] and "kpt.dev/injected-resource" in r["metadata"]["annotations"]:
        clusterName = r["spec"]["clusterName"]
    for r in resources:
      if krmfn.match_gvk(r, "infra.nephio.org/v1alpha1", "UPFDeployment"):
        r["metadata"]["name"] = "upf-" + clusterName
      if krmfn.match_gvk(r, "req.nephio.org/v1alpha1", "Interface"):
        if "annotations" in r["metadata"] and "specializer.nephio.org/owner" in r["metadata"]["annotations"]:
          r["metadata"]["annotations"][specializer.nephio.org/owner"] = "workload.nephio.org/v1alpha1.UPFDeployment.upf" + clusterName
      if krmfn.match_gvk(r, "req.nephio.org/v1alpha1", "Capacity"):
        if "annotations" in r["metadata"] and "specializer.nephio.org/owner" in r["metadata"]["annotations"]:
          r["metadata"]["annotations"][specializer.nephio.org/owner"] = "workload.nephio.org/v1alpha1.UPFDeployment.upf" + clusterName
      if krmfn.match_gvk(r, "req.nephio.org/v1alpha1", "DataNetwork"):
        if "annotations" in r["metadata"] and "specializer.nephio.org/owner" in r["metadata"]["annotations"]:
          r["metadata"]["annotations"][specializer.nephio.org/owner"] = "workload.nephio.org/v1alpha1.UPFDeployment.upf" + clusterName
  set_values(ctx.resource_list["items"])
